services:
  database:
    container_name: postgres-finsight-ai
    image: postgres:latest
    environment:
      POSTGRES_USER: ankit
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "7442:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: